apiVersion: v1
kind: Service
metadata:
  name: nginx-plus-ingress
  namespace: nginx-plus-ingress
  labels:
    app: nginx-plus-ingress
spec:
  type: ClusterIP
  ports:
    - name: http
      port: 80
      targetPort: 80
      protocol: TCP
    - name: https
      port: 443
      targetPort: 443
      protocol: TCP
  selector:
      app: nginx-plus-ingress
