kind: ConfigMap
apiVersion: v1
metadata:
  name: nginx-plus-config
  namespace: nginx-plus-ingress
data:
  proxy-connect-timeout: "10s"
 #proxy-protocol: "True"
 #real-ip-header: "proxy_protocol"
 #set-real-ip-from: "0.0.0.0/0"
  http-snippets: |
    map $jwt_claim_name $valid_user { 
      "Michael O'Leary" 1; 
    }
    auth_jwt_claim_set $jwt_groups groups; # here, we are setting a variable that will be a string, separated by commas. It is populated by the groups claim from the JWT which is an array.
