apiVersion: v1
kind: Namespace
metadata:
  name: nginx-plus-ingress 
  annotations:
    k8s.ovn.org/hybrid-overlay-external-gw: 10.142.6.60 #self ip of Vxlan tunnel
    k8s.ovn.org/hybrid-overlay-vtep: 10.0.2.7 #BIG-IP interface address rotatable to the OpenShift nodes
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: nginx-plus-ingress
  namespace: nginx-plus-ingress
